/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/actionBar/ActionBar.vue')['default']
    EmailActonBar: typeof import('./src/components/emailActionBar/EmailActonBar.vue')['default']
    EmailFallback: typeof import('./src/components/emailFallback/EmailFallback.vue')['default']
    EmailList: typeof import('./src/components/emailList/EmailList.vue')['default']
    EmailPreview: typeof import('./src/components/emailPreview/EmailPreview.vue')['default']
    EmptyState: typeof import('./src/components/emptyState/EmptyState.vue')['default']
    GenericLoading: typeof import('./src/components/genericLoading/GenericLoading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/loading/Loading.vue')['default']
    NewEmail: typeof import('./src/components/newEmail/NewEmail.vue')['default']
    ProfileMenu: typeof import('./src/components/profileMenu/ProfileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sideBar/SideBar.vue')['default']
  }
}
