export const MutationTypes = {
  LOGIN: {
      SET_AUTH: 'SET_AUTH',
      SET_LOGOUT: 'SET_LOGOUT'
  },
  USER: {
    SET_PROFILE: 'SET_PROFILE'
  },
  SET_STOMP_CLIENT: 'SET_STOMP_CLIENT',
  SET_LOADING_EMAIL_LIST: 'SET_LOADING_EMAIL_LIST',
  EMAIL: {
    SELECTED_ID: 'SELECTED_ID'
  }
}
